routes/web.php
<?php

Auth::routes();

Route::name('customer.')->group(function(){
  Route::resource('our-product', 'ProductController');
  Route::resource('career', 'CareerController');
  Route::resource('frequently-ask-question', 'FaqController');
  Route::resource('request-product', 'RequestProductController');
  Route::resource('contact-us', 'CustomerMessageController');
  Route::get('/', 'HomeController@landing')->name('landing');
  Route::get('about-us', 'HomeController@aboutUs')->name('about-us');
  Route::post('career-submit', 'CareerSubmitController')->name('career.submit');
  Route::post('drop-resume', 'ResumeController')->name('resume.store');
});
Route::prefix('admin')->name('admin.')->middleware('auth')->group(function(){
  Route::prefix('company')->name('company.')->group(function(){
    Route::delete('faq-category/delete/{category}', 'FaqController@destroyCategory')->name('faq-category.destroy');
    Route::get('social-media/change', 'SocialMediaController@edit')->name('social-media.edit-data');
    Route::post('social-media/update-social', 'SocialMediaController@update')->name('social-media.update-data');
    Route::get('social-media/destroy', 'SocialMediaController@destroy')->name('social-media.destroy-data');
    Route::resource('social-media', 'SocialMediaController')->except(['index']);
    Route::resource('image-asset', 'ImageAssetController')->only(['store', 'update']);
    Route::resource('profile', 'CompanyProfileController')->except('show');
    Route::resource('contact', 'CompanyContactController');
    Route::resource('client', 'ClientController')->except(['edit', 'update', 'show', 'create']);
    Route::resource('product', 'ProductController');
    Route::resource('faq', 'FaqController');
    Route::resource('career', 'CareerController');
    Route::resource('benefit', 'BenefitSectionController');
    Route::resource('free-sample', 'FreesampleSectionController');
    Route::resource('request-product', 'RequestProductController');
    Route::resource('message-customer', 'CustomerMessageController');
  });
  Route::prefix('meta-page')->name('meta-page.')->group(function(){
    Route::get('main-page', 'MetaPageController@index')->name('main');
    Route::get('career-page', 'MetaPageController@career')->name('career');
    Route::get('product-page', 'MetaPageController@product')->name('product');
    Route::get('about-page', 'MetaPageController@about')->name('about');
    Route::get('faq-page', 'MetaPageController@faq')->name('faq');
    Route::get('contact-us-page', 'MetaPageController@contactUs')->name('contact-us');
    Route::put('update/{id}', 'MetaPageController@updateMeta')->name('update');
    Route::put('update-thumbnail/{id}', 'MetaPageController@updateThumbnail')->name('updateThumbnail');
    Route::resource('keyword', 'KeywordController');
  });
  Route::prefix('page')->name('page.')->group(function(){
    Route::resource('home', 'FrontTextController');
    Route::resource('contact-us', 'FrontTextController');
    Route::resource('career', 'FrontTextController');
    Route::resource('product', 'FrontTextController');
    Route::resource('client', 'FrontTextController');
    Route::resource('career-cms', 'CareerController');
    Route::resource('image-asset', 'ImageAssetController')->only(['store', 'update']);
    Route::resource('product-image', 'ProductImageController');
  });
});

resources/views/about-us.blade.php
@extends('layouts.customer_master')
@section('meta-title'){{ $metaMain->title }}@endsection
@section('meta-desc'){{ $metaMain->description }}@endsection
@section('meta-img'){{ Storage::url($metaMain->thumbnail) }}@endsection
@section('meta-keyword')
@foreach($metaMain->keywords as $keyword)@if($loop->last){{ $keyword->keyword }}@else{{ $keyword->keyword . ', ' }}@endif @endforeach
@endsection
@section('title', 'About our company Dicson Synergy')
@section('page-name', 'about')
@section('header')
  <div class="container">
    <h1>
      <small class="secondary-text">About Us</small>
      <span class="heading-text">About our company <br> Dicson Synergy</span>
    </h1>
    <figure class="aboutHeader__figure">
      <img src="{{ asset('img/about_header.webp') }}" class="aboutHeader__img">
      <figcaption class="aboutHeader__caption">
        <p class="aboutHeader__slogan">your happines is our priority</p>
        <p class="aboutHeader__slogan">Give the best <br> Service for you</p>
      </figcaption>
    </figure>
  </div>
  <div class="headerBg"></div>
@endsection
@section('content')
  <section class="aboutBelieve">
    <div class="container">
      <h1>
        <small class="secondary-text">{{ $companyProfile->name }}</small>
        <span class="heading-text">We believe in being professional</span>
      </h1>
      <div class="row justify-content-between">
        <div class="col-12 col-md-6 col-lg-6 mb-4 mb-md-0">
          <p class="mb-4">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque eget at interdum vel mollis vitae.
            Tellus ut gravida odio sit tempor. Sed enim sagittis dolor, at nulla sem. Morbi eget porta est enim, sed dui ornare amet.
            Massa venenatis urna nunc, ornare dolor sit tristique volutpat.
          </p>
          <p>
            Tempus, at aliquam, donec euismod lacus, neque commodo et. Mi scelerisque neque fusce nibh. Facilisis felis nulla sit mi ut purus.
            Vestibulum, enim praesent ultrices sed suspendisse donec.
          </p>
        </div>
        <div class="col-12 col-md-4 col-lg-5 pr-5">
          <img src="{{ asset('img/about_believe.webp') }}" width="100%" class="aboutBelieve__img">
        </div>
      </div>
    </div>
  </section>
  <section class="aboutTeam">
    <div class="container">
      <h1>
        <small class="secondary-text">Great Team</small>
        <span class="heading-text">Work at Dickson Synergy</span>
      </h1>
      <div class="row justify-content-between mx-0 align-items-center align-items-lg-stretch flex-column flex-lg-row">
        <div class="col-12 col-lg-7 pl-lg-0">
          <img src="{{ asset('img/about_team1.webp') }}" class="aboutTeam__img">
        </div>
        <div class="col-12 col-lg-5 pl-lg-0">
          <img src="{{ asset('img/about_team2.webp') }}" class="aboutTeam__img aboutTeam__img--modified">
          <img src="{{ asset('img/vector_contact.svg') }}" class="aboutTeam__imgVector">
        </div>
      </div>
    </div>
  </section>
  <section class="aboutClient">
    <div class="container">
      <h1>
        <small class="secondary-text">Our Client</small>
        <span class="heading-text">Through the year we have sell a lot <br> product to our client</span>
      </h1>
      <div class="aboutClientSlider">
        @foreach ($clients as $client)
          <img src="{{ Storage::url($client->logo) }}" class="aboutClientSlider__img">
        @endforeach
      </div>
    </div>
    <img src="{{ asset('img/icon/vector_about.svg') }}" class="aboutClient__vector">
  </section>
@endsection

resources/views/contact-us.blade.php
@extends('layouts.customer_master')
@section('meta-title'){{ $metaMain->title }}@endsection
@section('meta-desc'){{ $metaMain->description }}@endsection
@section('meta-img'){{ Storage::url( $metaMain->thumbnail) }}@endsection
@section('meta-keyword')
@foreach($metaMain->keywords as $keyword)@if($loop->last){{ $keyword->keyword }}@else{{ $keyword->keyword . ', ' }}@endif @endforeach
@endsection
@section('title', 'Best Solution Protect your Product Cargo')
@section('page-name', 'contactUs')
@section('header')
  <div class="container">
    <h1>
      <small class="secondary-text">Contact us</small>
      <span class="heading-text">Feel free to <br> contact us</span>
    </h1>
  </div>
@endsection
@section('content')
  <div class="container">
    <div class="alert-success" style="display: none">
      Your message has been sent. We can reply at maximum 24 hours from now!
    </div>

    <div class="showbox" style="display: none">
      <div class="loader">
        <svg class="circular" viewBox="25 25 50 50">
          <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
        </svg>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-6 contact-fill">
        <h2 class="heading-text">Get in contact</h2>
        <form class="form" method="post">
          @csrf
          <div class="form__box">
            <label for="name" class="form__label">name</label>
            <input type="text" class="form__input" name="name" placeholder="your name">
          </div>
          <div class="form__box">
            <label for="country" class="form__label input-required">country</label>
            <input type="text" class="form__input" name="country" value="{{ old('country') }}" placeholder="your country" required>
          </div>
          <div class="form__box">
            <label for="email" class="form__label input-required">email</label>
            <input type="text" class="form__input" name="email" value="{{ old('email') }}" placeholder="your email address" required>
          </div>
          <div class="form__box">
            <label for="company_name" class="form__label">company name</label>
            <input type="text" class="form__input" name="company_name" value="{{ old('company_name') }}" placeholder="your company name">
          </div>
          <div class="form__box">
            <label for="message" class="form__label input-required">Your message</label>
            <textarea name="message" rows="8" class="form__input" placeholder="your text here" required></textarea>
          </div>
          <div class="form__box form__box--no-label">
            <label class="form-check-label" for="accept">
              <input name="accept" id="accept" type="radio" class="form-check-input mr-2">
              I allow to store and process my information for the purpose given in this contact form.
              <span class="radio-circle"></span>
            </label>
          </div>
          <div class="row mx-0 justify-content-end">
            <a href="https://wa.me/{{ Str::slug($companyContact->whatsapp, '') }}" class="btn-primary contact-fill__btn mb-3 mb-md-0">
              Instant Contact <i class='bx bxl-whatsapp'></i>
            </a>
            <button type="submit" class="btn-primary ml-lg-4" disabled>Send Message</button>
          </div>
        </form>
      </div>
      <div class="col-12 col-md-6 contact-info">
        <h2 class="heading-text">Office</h2>
        <p class="contact-info__company-name">PT {{ $companyProfile->name }}</p>
        <address class="contact-info__address">{{ $companyContact->address }}</address>
        <div class="contact-info__direct">
          <a href="mailto:{{ $companyContact->email }}?subject=Message From Customer" class="contact-info__link">
            <img src="{{ asset('img/icon/mail.svg') }}" height="20">
            {{ $companyContact->email }}
          </a>
          <a href="tel:{{ Str::slug($companyContact->telphone, '') }}" class="contact-info__link">
            <img src="{{ asset('img/icon/telphone.svg') }}" height="20">
            {{ $companyContact->telphone }}
          </a>
        </div>
        <div class="contact-info__img">
          <img src="{{ Storage::url($imageAsset->img_contact) }}" class="">
          <img src="{{ asset('img/vector_contact.svg') }}" class="bg-accessories d-none d-lg-block" height="150">
        </div>
      </div>
    </div>
  </div>
@endsection
@section('script')
  <script>
    $(document).ready(function() {
      $("form").submit(function(e) {
        e.preventDefault();
        $.ajaxSetup({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
          }
        });
        $.ajax({
          url: '{{ route('customer.contact-us.store') }}',
          method: 'post',
          data: {
            name: $(".form__input[name='name']").val(),
            country: $(".form__input[name='country']").val(),
            email: $(".form__input[name='email']").val(),
            company_name: $(".form__input[name='company_name']").val(),
            message: $(".form__input[name='message']").val(),
          },
          beforeSend: function(){
            $('.showbox').show();
          },
          complete: function() {
            $(".showbox").hide("slow");
          },
          success: function(result){
            $("form")[0].reset();
            $('.alert-success').show().delay(2000).fadeOut();
          },
          error: function(xhr, status, error) {
            var err = eval("(" + xhr.responseText + ")");
            console.log(err.Message);
          }
        });
      });

      $("input[name='accept']").change(function() {
        if ($(this).is(":checked")) {
          $("[type='submit']").prop('disabled', false);
        }
        else {
          $("[type='submit']").prop('disabled', true);
        }
      });
    });
  </script>
@endsection

resources/views/faq.blade.php
@extends('layouts.customer_master')
@section('meta-title'){{ $metaMain->title }}@endsection
@section('meta-desc'){{ $metaMain->description }}@endsection
@section('meta-img'){{ Storage::url( $metaMain->thumbnail) }}@endsection
@section('meta-keyword')
@foreach($metaMain->keywords as $keyword)@if($loop->last){{ $keyword->keyword }}@else{{ $keyword->keyword . ', ' }}@endif @endforeach
@endsection
@section('title', 'Best Solution Protect your Product Cargo')
@section('page-name', 'faq')
@section('css')
  <link rel="stylesheet" href="{{ asset('external/vertical-tabs/dist/jquery.tabs.min.css') }}">
@endsection
@section('header')
  <div class="container">
    <h1>
      <small class="secondary-text">Help center</small>
      <span class="heading-text">Need Help or <br class="d-none d-lg-block"> Question?</span>
    </h1>
  </div>
@endsection
@section('content')
  <section class="top mb-4">
    <div class="container">
      <div class="row">
        <div class="col">
          <h2>
            <small class="secondary-text">Have a question?</small>
            <span class="heading-text">FAQ</span>
          </h2>
        </div>
      </div>
      <hr class="top__divider">
      <div class="row py-3 py-lg-5">
        <div class="col">
          <div class="jq-tab-wrapper faqTab">
            <div class="jq-tab-menu faqTab__menu">
              @foreach ($faqCategory as $category)
                <div class="jq-tab-title faqTab__title {{ $loop->first ? 'active' : '' }}" data-tab="{{ $category->category }}">
                  <p>{{ $category->category }}</p>
                </div>
              @endforeach
            </div>
            <div class="jq-tab-content-wrapper faqContent">
              @foreach ($faqCategory as $category)
                <div class="jq-tab-content {{ $loop->first ? 'active' : '' }}" data-tab="{{ $category->category }}">
                  @foreach ($category->faqVisible as $faq)
                    <details class="faqContent__item">
                      <summary>{{ $faq->question }} <i class='bx bxs-down-arrow'></i></summary>
                      {{ $faq->answer }}
                    </details>
                  @endforeach
                </div>
              @endforeach
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <p class="mb-3">Can't find what you're <br class="d-lg-none"> looking for?</p>
          <p class="mb-3">Email your questions to <a href="mailto:info@dicksonsynergy.com" class="text-orange">info@dicksonsynergy.com</a></p>
        </div>
      </div>
    </div>
  </section>
  <section class="questioning-dickson">
    <div class="container">
      <div class="row align-items-center justify-content-center flex-column">
        <div class="col text-center">
          <img src="{{ asset('img/icon/question-mark.svg') }}">
          <p class="questioning-dickson__question">Questions about joining Dickson?</p>
          <p class="questioning-dickson__answer">fell free to <a class="questioning-dickson__contact-link" href="{{ route('customer.contact-us.index') }}">contact us</a></p>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/landing-page.blade.php
@extends('layouts.customer_master')
@section('meta-title'){{ $metaMain->title }}@endsection
@section('meta-desc'){{ $metaMain->description }}@endsection
@section('meta-img'){{ Storage::url( $metaMain->thumbnail) }}@endsection
@section('meta-keyword')
@foreach($metaMain->keywords as $keyword)@if($loop->last){{ $keyword->keyword }}@else{{ $keyword->keyword . ', ' }}@endif @endforeach
@endsection
@section('title', 'Best Solution Protect your Product Cargo')
@section('page-name', 'landing')
@section('header')
  <div class="container">
    <figure class="landingHeader">
      <img class="header__img" src="{{ Storage::url($imageAsset->header_home) }}" alt="Dickson synergy header">
      <img src="{{ asset('img/vector_contact.svg') }}" class="bg-accessories">
      <figcaption class="header__info">
        <small class="header__company-name">{{ $companyProfile->name }}</small>
        <h1 class="header__slogan">{{ $companyProfile->title }}</h1>
        <p class="header__description">{{ $companyProfile->description }}</p>
      </figcaption>
    </figure>
    <img src="{{ asset('img/icon/bottom-arrow.svg') }}" class="header__arrow">
  </div>
@endsection
@section('content')
  <section class="product">
    <div class="container">
      <h1>
        <small class="secondary-text">{{ $frontText->product_secondary }}</small>
        <span class="heading-text">{{ $frontText->product_heading }}</span>
      </h1>
      <div class="row product__slider">
          @foreach ($productRecommend as $recomended)
            <a href="{{ route('customer.our-product.show', $recomended->product->slug) }}">
              <div class="col px-lg-3">
                <figure class="product__item">
                  <div class="product__image">
                    <img src="{{ Storage::url($recomended->image) }}">
                  </div>
                  <figcaption class="product__caption">
                    <p class="product__title">{{ $recomended->product->title }}</p>
                    <p class="product__subtitle">{{ $recomended->product->subtitle }}</p>
                  </figcaption>
                </figure>
              </div>
            </a>
          @endforeach
      </div>
    </div>
  </section>
  <section class="getFree">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-md-7 col-lg-4 getFree__info">
          <h1>
            <small class="secondary-text">{{ $frontText->free_sample_secondary }}</small>
            <span class="heading-text">{{ $frontText->free_sample_heading }}</span>
          </h1>
          <figure class="mb-4 mb-lg-0">
            <img class="getFree__img" src="{{ Storage::url($freeSample->cover) }}">
            <img src="{{ asset('img/vector_contact.svg') }}" class="bg-accessories d-none d-lg-block">
            <figcaption class="getFree__caption">
              <p class="mb-3 getFree__heading">{{ $freeSample->heading }}</p>
              <p class="getFree__subheading">{{ $freeSample->subheading }}</p>
            </figcaption>
          </figure>
        </div>
        <div class="col-12 col-lg-5 getFree_desc">
          {!! $frontText->free_sample_desc !!}
          <a href="{{ route('customer.our-product.index') }}" class="getFree__btn">{{ $frontText->btn_free_sample }}</a>
        </div>
      </div>
    </div>
  </section>
  <section class="benefit">
    <div class="container">
      <h1 class="mb-4">
        <small class="secondary-text">{{ $frontText->benefit_secondary }}</small>
        <span class="heading-text">{{ $frontText->benefit_heading }}</span>
      </h1>
      <div class="row">
        @foreach ($benefits as $benefit)
          <div class="col-12 col-lg-3 px-lg-4">
            <figure class="benefit__item">
              <img class="benefit__img" src="{{ Storage::url($benefit->icon) }}" alt="Benefit When You Trust Dickson">
              <figcaption class="benefit__detail">
                <h2 class="benefit__title">{{ $benefit->title }}</h2>
                <p class="benefit__desc">{{ $benefit->description }}</p>
              </figcaption>
            </figure>
          </div>
        @endforeach
      </div>
    </div>
  </section>
@endsection

resources/views/send_mail.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <style>
      div {
        width: 100%;
      }
      div:first-child {
        display: flex;
        justify-content:
        space-between;
        padding: 30px 0;
      }
      div:last-child {
        margin: 50px 0;text-align: center;
      }
    </style>
  </head>
  <body>
    <div>
      <p>Sender : {{ $nameSender . '(' . $emailSender . ')' }}</p>
      @if ($companySender)
      <p>From Company {{ $companySender }}</p>
      @endif
      <p>From Country : {{ $countrySender }}</p>
    </div>
    <div>
      <p>{{ $bodySender }}</p>
    </div>

  </body>
</html>