routes/web.php
<?php

Auth::routes();

Route::name('customer.')->group(function(){
  Route::resource('our-product', 'ProductController');
  Route::resource('career', 'CareerController');
  Route::resource('frequently-ask-question', 'FaqController');
  Route::resource('request-product', 'RequestProductController');
  Route::resource('contact-us', 'CustomerMessageController');
  Route::get('/', 'HomeController@landing')->name('landing');
  Route::get('about-us', 'HomeController@aboutUs')->name('about-us');
  Route::post('career-submit', 'CareerSubmitController')->name('career.submit');
  Route::post('drop-resume', 'ResumeController')->name('resume.store');
});
Route::prefix('admin')->name('admin.')->middleware('auth')->group(function(){
  Route::prefix('company')->name('company.')->group(function(){
    Route::delete('faq-category/delete/{category}', 'FaqController@destroyCategory')->name('faq-category.destroy');
    Route::get('social-media/change', 'SocialMediaController@edit')->name('social-media.edit-data');
    Route::post('social-media/update-social', 'SocialMediaController@update')->name('social-media.update-data');
    Route::get('social-media/destroy', 'SocialMediaController@destroy')->name('social-media.destroy-data');
    Route::resource('social-media', 'SocialMediaController')->except(['index']);
    Route::resource('image-asset', 'ImageAssetController')->only(['store', 'update']);
    Route::resource('profile', 'CompanyProfileController')->except('show');
    Route::resource('contact', 'CompanyContactController');
    Route::resource('client', 'ClientController')->except(['edit', 'update', 'show', 'create']);
    Route::resource('product', 'ProductController');
    Route::resource('faq', 'FaqController');
    Route::resource('career', 'CareerController');
    Route::resource('benefit', 'BenefitSectionController');
    Route::resource('free-sample', 'FreesampleSectionController');
    Route::resource('request-product', 'RequestProductController');
    Route::resource('message-customer', 'CustomerMessageController');
  });
  Route::prefix('meta-page')->name('meta-page.')->group(function(){
    Route::get('main-page', 'MetaPageController@index')->name('main');
    Route::get('career-page', 'MetaPageController@career')->name('career');
    Route::get('product-page', 'MetaPageController@product')->name('product');
    Route::get('about-page', 'MetaPageController@about')->name('about');
    Route::get('faq-page', 'MetaPageController@faq')->name('faq');
    Route::get('contact-us-page', 'MetaPageController@contactUs')->name('contact-us');
    Route::put('update/{id}', 'MetaPageController@updateMeta')->name('update');
    Route::put('update-thumbnail/{id}', 'MetaPageController@updateThumbnail')->name('updateThumbnail');
    Route::resource('keyword', 'KeywordController');
  });
  Route::prefix('page')->name('page.')->group(function(){
    Route::resource('home', 'FrontTextController');
    Route::resource('contact-us', 'FrontTextController');
    Route::resource('career', 'FrontTextController');
    Route::resource('product', 'FrontTextController');
    Route::resource('client', 'FrontTextController');
    Route::resource('career-cms', 'CareerController');
    Route::resource('image-asset', 'ImageAssetController')->only(['store', 'update']);
    Route::resource('product-image', 'ProductImageController');
  });
});

resources/views/admin/partial/modal_add_benefit.blade.php
<div class="modal fade" id="modalAddBenefit" tabindex="-1" role="dialog" aria-labelledby="modalAddBenefitLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add new client</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.company.benefit.store') }}"  id="formAddBenefit" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label for="benefit_title">Title</label>
          <input type="text" class="form-control" id="benefit_title" name="title" placeholder="Benefit Title">
        </div>
        <div class="form-group">
          <label for="benefit_description">Description</label>
          <textarea name="description" rows="8" class="form-control" id="benefit_description" placeholder="Benefit Description"></textarea>
        </div>
        <div class="form-group">
          <div class="custom-file">
            <input type="file" class="custom-file-input" name="icon" data-img="iconPreview" id="icon" accept="image/*">
            <label class="custom-file-label" for="icon">Benefit Icon</label>
          </div>
        </div>
        <img src="" class="img-preview" data-preview="iconPreview" height="50">
      </form>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success" form="formAddBenefit">Add New Benefit</button>
      </div>
    </div>
  </div>
</div>

resources/views/admin/partial/modal_edit_careerText.blade.php
<div class="modal fade" id="career_subheading_header" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Subheading header</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_subheading_header">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_subheading_header" class="form-control" value="{{ $dynamicText->career_subheading_header }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_heading_header" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Heading header</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_heading_header">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_heading_header" class="form-control" value="{{ $dynamicText->career_heading_header }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_btn_job" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Button Find Jobs</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_btn_job">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_btn_job" class="form-control" value="{{ $dynamicText->career_btn_job }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_section_value_subheading" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Section <u>our value & benefit</u> subheading</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_section_value_subheading">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_section_value_subheading" class="form-control" value="{{ $dynamicText->career_section_value_subheading }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_section_value_heading" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Section <u>our value & benefit</u> heading</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_section_value_heading">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_section_value_heading" class="form-control" value="{{ $dynamicText->career_section_value_heading }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_section_value_description" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Section <u>our value & benefit</u> description</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_section_value_description">
        @csrf @method('PUT')
        <div class="form-group">
          <textarea name="career_section_value_description" rows="8" class="form-control">{{ $dynamicText->career_section_value_description }}</textarea>
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_team_subheading" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Section <u>great team</u> subheading</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_team_subheading">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_team_subheading" class="form-control" value="{{ $dynamicText->career_team_subheading }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_team_heading" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Section <u>great team</u> heading</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_team_heading">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_team_heading" class="form-control" value="{{ $dynamicText->career_team_heading }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_job_subheading" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Section <u>job available</u> subheading</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_job_subheading">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_job_subheading" class="form-control" value="{{ $dynamicText->career_job_subheading }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_job_heading" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Section <u>job available</u> heading</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_job_heading">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_job_heading" class="form-control" value="{{ $dynamicText->career_job_heading }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_resume_subheading" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Drop resume subheading</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_resume_subheading">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_resume_subheading" class="form-control" value="{{ $dynamicText->career_resume_subheading }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_resume_heading" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Drop resume heading</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_resume_heading">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_resume_heading" class="form-control" value="{{ $dynamicText->career_resume_heading }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="career_resume_btn" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Drop resume button text</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.career-cms.update', $dynamicText->id) }}" method="post" id="career_resume_btn">
        @csrf @method('PUT')
        <div class="form-group">
          <input type="text" name="career_resume_btn" class="form-control" value="{{ $dynamicText->career_resume_btn }}">
        </div>
        <button type="submit" class="btn btn-success btn-block">Update Text</button>
      </form>
    </div>
  </div>
</div>

resources/views/admin/partial/modal_edit_contactUs.blade.php
<div class="modal fade" id="contact_us_header" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Header page contact us</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.contact-us.update', $dynamicText->id) }}" id="updateContactHeading" method="post">
        @csrf @method('PUT')
        <div class="form-group">
          <label for="contact_us_header">Heading text</label>
          <input id="contact_us_header" name="contact_us_header" placeholder="Update button free sample text" type="text"
          class="form-control" value="{{ $dynamicText->contact_us_heading }}">
        </div>
      </form>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success" form="updateContactHeading">Update Text</button>
      </div>
    </div>
  </div>
</div>

resources/views/admin/partial/modal_edit_freeSample.blade.php
<div class="modal fade" id="modalFreeSample" tabindex="-1" role="dialog" aria-labelledby="modalFreeSampleLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit {{ $freeSample->heading }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
              <form action="{{ route('admin.company.free-sample.update', $freeSample->id) }}" id="formEditFreeSample"
              method="post" enctype="multipart/form-data">
                @csrf @method('PUT')
                <div class="form-group">
                  <label for="title">Title</label>
                  <input type="text" id="title" placeholder="Title Text" name="heading" class="form-control" value="{{ $freeSample->heading }}">
                </div>
                <div class="form-group">
                  <label for="description">Short Description</label>
                  <input type="text" id="description" placeholder="Short Description" name="description"
                  class="form-control" value="{{ $freeSample->subheading }}">
                </div>
                <div class="form-group">
                  <label for="longDescription">Free sample long description</label>
                  <textarea name="longDescription" id="longDescription"
                  rows="8" class="form-control">{{ $dynamicText->free_sample_desc }}</textarea>
                </div>
                <div class="form-group">
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" name="cover" id="cover">
                    <label class="custom-file-label" for="cover">Change Cover</label>
                  </div>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary" form="formEditFreeSample">Update Section Get Free Sample</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/partial/modal_edit_text.blade.php
<div class="modal fade modal-edit-dynamicText" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{-- text from js --}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="modal-body" action="{{ route('admin.page.home.update', $dynamicText->id) }}" method="post">
        @csrf @method('PUT')
        <div class="form-group">
          <input name="btn_free_sample" id="btn_free_sample" placeholder="Update button free sample text" type="text" class="form-control">
        </div>
      </form>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success">Update Text</button>
      </div>
    </div>
  </div>
</div>