routes/web.php
<?php

Auth::routes();

Route::name('customer.')->group(function(){
  Route::resource('our-product', 'ProductController');
  Route::resource('career', 'CareerController');
  Route::resource('frequently-ask-question', 'FaqController');
  Route::resource('request-product', 'RequestProductController');
  Route::resource('contact-us', 'CustomerMessageController');
  Route::get('/', 'HomeController@landing')->name('landing');
  Route::get('about-us', 'HomeController@aboutUs')->name('about-us');
  Route::post('career-submit', 'CareerSubmitController')->name('career.submit');
  Route::post('drop-resume', 'ResumeController')->name('resume.store');
});
Route::prefix('admin')->name('admin.')->middleware('auth')->group(function(){
  Route::prefix('company')->name('company.')->group(function(){
    Route::delete('faq-category/delete/{category}', 'FaqController@destroyCategory')->name('faq-category.destroy');
    Route::get('social-media/change', 'SocialMediaController@edit')->name('social-media.edit-data');
    Route::post('social-media/update-social', 'SocialMediaController@update')->name('social-media.update-data');
    Route::get('social-media/destroy', 'SocialMediaController@destroy')->name('social-media.destroy-data');
    Route::resource('social-media', 'SocialMediaController')->except(['index']);
    Route::resource('image-asset', 'ImageAssetController')->only(['store', 'update']);
    Route::resource('profile', 'CompanyProfileController')->except('show');
    Route::resource('contact', 'CompanyContactController');
    Route::resource('client', 'ClientController')->except(['edit', 'update', 'show', 'create']);
    Route::resource('product', 'ProductController');
    Route::resource('faq', 'FaqController');
    Route::resource('career', 'CareerController');
    Route::resource('benefit', 'BenefitSectionController');
    Route::resource('free-sample', 'FreesampleSectionController');
    Route::resource('request-product', 'RequestProductController');
    Route::resource('message-customer', 'CustomerMessageController');
  });
  Route::prefix('meta-page')->name('meta-page.')->group(function(){
    Route::get('main-page', 'MetaPageController@index')->name('main');
    Route::get('career-page', 'MetaPageController@career')->name('career');
    Route::get('product-page', 'MetaPageController@product')->name('product');
    Route::get('about-page', 'MetaPageController@about')->name('about');
    Route::get('faq-page', 'MetaPageController@faq')->name('faq');
    Route::get('contact-us-page', 'MetaPageController@contactUs')->name('contact-us');
    Route::put('update/{id}', 'MetaPageController@updateMeta')->name('update');
    Route::put('update-thumbnail/{id}', 'MetaPageController@updateThumbnail')->name('updateThumbnail');
    Route::resource('keyword', 'KeywordController');
  });
  Route::prefix('page')->name('page.')->group(function(){
    Route::resource('home', 'FrontTextController');
    Route::resource('contact-us', 'FrontTextController');
    Route::resource('career', 'FrontTextController');
    Route::resource('product', 'FrontTextController');
    Route::resource('client', 'FrontTextController');
    Route::resource('career-cms', 'CareerController');
    Route::resource('image-asset', 'ImageAssetController')->only(['store', 'update']);
    Route::resource('product-image', 'ProductImageController');
  });
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ $companyProfile->name }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ $companyProfile->name }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/customer_master.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr" id="customerMaster">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="og:title" content="@yield('meta-title')">
    <meta name="og:description" content='@yield("meta-desc")'>
    <meta name="keywords" content="@yield('meta-keyword')">
    <meta name="og:image" content="@yield('meta-img')">
    <meta name="og:url" content="{{ URL::full() }}">
    <meta name="og:type" content="website">
    <link rel="shortcut icon" href="{{ Storage::url($imageAsset->favicon) }}">
    <link rel="icon" type="image/png" href="{{ Storage::url($imageAsset->favicon) }}" sizes="192x192">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ Storage::url($imageAsset->favicon) }}">
    <link rel="stylesheet" href="{{ asset('css/customer.css') }}">
    <link href='https://unpkg.com/boxicons@2.0.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{{ asset('external/slick/slick.css') }}">
    <link rel="stylesheet" href="{{ asset('external/slick/slick-theme.css') }}">
    @yield('css')
    <title>Dickson Synergy - @yield('title')</title>
  </head>
  <body id="@yield('page-name')Page">
    <header>
      <nav>
        <div class="container">
          <li class="nav__list">
            <a href="{{ route('customer.landing') }}" class="nav__brand">
              <img src="{{ Storage::url($imageAsset->logo_menu) }}" alt="Dickson Logo">
            </a>
            <a href="javascript:void(0);" class="nav__open">
              <i class='bx bx-menu-alt-right'></i>
            </a>
          </li>
          <li class="nav__list">
            <a class="nav__link" href="{{ route('customer.landing') }}">Home</a>
          </li>
          <li class="nav__list">
            <a class="nav__link" href="{{ route('customer.about-us') }}">About Us</a>
          </li>
          <li class="nav__list">
            <a class="nav__link {{ \Request::is('our-product/*') ? 'nav__link--active' : '' }}"
            href="{{ route('customer.our-product.index') }}">
              Product
            </a>
          </li>
          <li class="nav__list">
            <a class="nav__link {{ \Request::is('career/*') ? 'nav__link--active' : '' }}" href="{{ route('customer.career.index') }}">
              Career
            </a>
          </li>
          <li class="nav__list">
            <a class="nav__link" href="{{ route('customer.frequently-ask-question.index') }}">FAQ</a>
          </li>
          <li class="nav__list">
            <a class="nav__link" href="{{ route('customer.contact-us.index') }}">Contact us</a>
          </li>
        </div>
      </nav>
      @yield('header')
    </header>
    <main>
      @yield('content')
    </main>
    <footer>
      <div class="container">
        <div class="row">
          <div class="footer__left">
            <a href="{{ route('customer.landing') }}">
              <img src="{{ Storage::url($imageAsset->logo_footer) }}" alt="Dickson Logo">
            </a>
            <ul class="footer_media">
              @foreach ($companySocial as $social)
                <li>
                  <a href="https://{{ $social->social_media . '.com/' . $social->username }}" target="_blank" class="footer__link">
                    <img src="{{ Storage::url($social->icon) }}" height="30">
                  </a>
                </li>
              @endforeach
            </ul>
            <small class="footer__legal">&copy; {{ date('Y') . ' '. $companyProfile->copyright }}</small>
          </div>
          <div class="footer__right">
            <ul>
              <li>
                <a href="{{ route('customer.about-us') }}" class="footer__link footer__link--bold">About Us</a>
              </li>
              <li>
                <a href="{{ route('customer.our-product.index') }}" class="footer__link footer__link--bold">Product</a>
              </li>
              <li>
                <a href="{{ route('customer.career.index') }}" class="footer__link footer__link--bold">Career</a>
              </li>
              <li>
                <a href="{{ route('customer.frequently-ask-question.index') }}" class="footer__link footer__link--bold">FAQ</a>
              </li>
              <li>
                <a href="{{ route('customer.contact-us.index') }}" class="footer__link footer__link--bold">Contact us</a>
              </li>
            </ul>
            <ul>
              <li>
                <a href="mailto:{{ $companyContact->email }}" class="footer__link">{{ $companyContact->email }}</a>
              </li>
              <li>
                <a href="tel:{{ $companyContact->telphone }}" class="footer__link">{{ $companyContact->telphone }}</a>
              </li>
              <li>
                <a href="https://www.google.com/maps/search/{{ Str::slug($companyContact->address), '+' }}" class="footer__link">
                  {{ $companyContact->address }}
                </a>
              </li>
              <li>
                <a href="{{ $companyContact->location }}" class="footer__link">{{ $companyContact->location }}</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    @yield('partial')
    <script src="{{ asset('js/jquery.min.js') }}" charset="utf-8" type="text/javascript"></script>
    <script src="{{ asset('external/slick/slick.min.js') }}" charset="utf-8"></script>
    <script src="{{ asset('external/vertical-tabs/dist/jquery.tabs.min.js') }}" charset="utf-8"></script>
    @yield('script')
    <script src="{{ asset('js/customer.js') }}" charset="utf-8"></script>
  </body>
</html>