routes/web.php
<?php

Auth::routes();

Route::name('customer.')->group(function(){
  Route::resource('our-product', 'ProductController');
  Route::resource('career', 'CareerController');
  Route::resource('frequently-ask-question', 'FaqController');
  Route::resource('request-product', 'RequestProductController');
  Route::resource('contact-us', 'CustomerMessageController');
  Route::get('/', 'HomeController@landing')->name('landing');
  Route::get('about-us', 'HomeController@aboutUs')->name('about-us');
  Route::post('career-submit', 'CareerSubmitController')->name('career.submit');
  Route::post('drop-resume', 'ResumeController')->name('resume.store');
});
Route::prefix('admin')->name('admin.')->middleware('auth')->group(function(){
  Route::prefix('company')->name('company.')->group(function(){
    Route::delete('faq-category/delete/{category}', 'FaqController@destroyCategory')->name('faq-category.destroy');
    Route::get('social-media/change', 'SocialMediaController@edit')->name('social-media.edit-data');
    Route::post('social-media/update-social', 'SocialMediaController@update')->name('social-media.update-data');
    Route::get('social-media/destroy', 'SocialMediaController@destroy')->name('social-media.destroy-data');
    Route::resource('social-media', 'SocialMediaController')->except(['index']);
    Route::resource('image-asset', 'ImageAssetController')->only(['store', 'update']);
    Route::resource('profile', 'CompanyProfileController')->except('show');
    Route::resource('contact', 'CompanyContactController');
    Route::resource('client', 'ClientController')->except(['edit', 'update', 'show', 'create']);
    Route::resource('product', 'ProductController');
    Route::resource('faq', 'FaqController');
    Route::resource('career', 'CareerController');
    Route::resource('benefit', 'BenefitSectionController');
    Route::resource('free-sample', 'FreesampleSectionController');
    Route::resource('request-product', 'RequestProductController');
    Route::resource('message-customer', 'CustomerMessageController');
  });
  Route::prefix('meta-page')->name('meta-page.')->group(function(){
    Route::get('main-page', 'MetaPageController@index')->name('main');
    Route::get('career-page', 'MetaPageController@career')->name('career');
    Route::get('product-page', 'MetaPageController@product')->name('product');
    Route::get('about-page', 'MetaPageController@about')->name('about');
    Route::get('faq-page', 'MetaPageController@faq')->name('faq');
    Route::get('contact-us-page', 'MetaPageController@contactUs')->name('contact-us');
    Route::put('update/{id}', 'MetaPageController@updateMeta')->name('update');
    Route::put('update-thumbnail/{id}', 'MetaPageController@updateThumbnail')->name('updateThumbnail');
    Route::resource('keyword', 'KeywordController');
  });
  Route::prefix('page')->name('page.')->group(function(){
    Route::resource('home', 'FrontTextController');
    Route::resource('contact-us', 'FrontTextController');
    Route::resource('career', 'FrontTextController');
    Route::resource('product', 'FrontTextController');
    Route::resource('client', 'FrontTextController');
    Route::resource('career-cms', 'CareerController');
    Route::resource('image-asset', 'ImageAssetController')->only(['store', 'update']);
    Route::resource('product-image', 'ProductImageController');
  });
});

resources/views/admin/company/benefit/edit.blade.php
@extends('layouts.admin_master')
@section('title', 'Company Client')
@section('page-name', 'company_client')
@section('page-header')
  Edit {{ $benefit->title }} Details
  <form action="{{ route('admin.company.benefit.destroy', $benefit->id) }}" method="post">
    @csrf @method("DELETE")
    <button type="submit" class="btn btn-link text-danger"><i class='bx bxs-trash-alt'></i></button>
  </form>
@endsection
@section('content')
  <div class="row">
    <div class="col-12">
      <img src="{{ Storage::url($benefit->icon) }}" class="mb-4 d-block mx-auto img-preview" height="100" data-preview="benefitIcon">
      <div class="card">
        <form action="{{ route('admin.company.benefit.update', $benefit->id) }}" class="card-body" method="post" enctype="multipart/form-data">
          @csrf @method("PUT")
          <input type="hidden" name="id" value="{{ $benefit->id }}">
          <div class="form-group">
            <label for="title">Title</label>
            <input type="text" id="title" class="form-control" name="title" placeholder="Eg: Maintain long shelf lives" value="{{ $benefit->title }}">
          </div>
          <div class="form-group">
            <label for="description">Description</label>
            <textarea name="description" id="description" rows="8" class="form-control"
            placeholder="Eg: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, rem.">{{ $benefit->description }}</textarea>
          </div>
          <div class="form-group">
            <div class="custom-file col">
              <input type="file" class="custom-file-input" name="icon" id="icon" data-img="benefitIcon" accept="image/*">
              <label class="custom-file-label" for="icon">Change Icon</label>
            </div>
          </div>
          <button type="submit" class="btn btn-success btn-block btn-lg">Change Detail</button>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/company/benefit/index.blade.php
<div class="col-12 col-md-6 mb-3 mb-md-0">
  <div class="card">
    <div class="card-header">
      <h5 class="card-title mb-0">Content Section Benefit</h5>
      <button type="button" class="btn btn-link" data-toggle="modal" data-target="#modalAddBenefit"><i class='bx bx-plus bx-sm'></i></button>
    </div>
    <div class="card-body p-0">
      <div id="benefitSlider" class="carousel slide pointer-event">
        <div class="carousel-inner">
          @foreach ($benefitSlider as $slider)
            <div class="carousel-item {{ $loop->first ? 'active' : '' }}" data-slider="slider{{ $slider->id }}">
              <img class="d-block w-100" src="{{ Storage::url($slider->icon) }}" title="{{ $slider->name }}">
              <div class="carousel-caption d-none d-md-block">
                <h5 class="text-dark">
                  {{ $slider->title }}
                  <a href="{{ route('admin.company.benefit.edit', $slider->id) }}" class="ml-2"><i class='bx bxs-edit-alt' ></i></a>
                </h5>
                <p class="text-dark">{{ $slider->description }}</p>
              </div>
            </div>
          @endforeach
        </div>
        <a class="carousel-control-prev" href="#benefitSlider" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"><i class='bx bx-chevron-left'></i></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#benefitSlider" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"><i class='bx bx-chevron-right'></i></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>